doctrine:
    dbal:
        driver: 'pdo_sqlite'
        server_version: '3.37.2'
        url: '%env(resolve:DATABASE_URL)%'
        charset: UTF8
        user: 'user'
        password: 'pass'


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
